---
title: "Journal (reproducible report)"
author: "Amr Mahmoud"
date: "2020-11-25"
output:
  html_document:
    toc: true
    toc_float: true
    collapsed: false
    number_sections: true
    toc_depth: 3
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(message=FALSE,warning=FALSE, cache=TRUE)
```
# Introduction to tidyverse
## Libraries
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library("writexl")
```
##importing data
### importing data
```{r}
bikes_tbl <- readxl:: read_excel(path = "DS_101/00_data/01_bike_sales/01_raw_data/bikes.xlsx")

orderlines_tbl <- readxl::read_excel("DS_101/00_data/01_bike_sales/01_raw_data/orderlines.xlsx")

bikeshops_tbl  <- readxl::read_excel("DS_101/00_data/01_bike_sales/01_raw_data/bikeshops.xlsx")
```
## Mergring data
```{r}
left_join(orderlines_tbl, bikes_tbl, by = c("product.id" = "bike.id"))
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))

```
## Data sorting and binding with other data tables 
```{r}
bike_orderlines_wrangled_city_separated_tbl <- bike_orderlines_joined_tbl %>%
  separate(col    = category,
           into   = c("category.1", "category.2", "category.3"),
           sep    = " - ") %>% 
  
  # Separate city and state 
  
  separate(col    = location,
           into   = c("City", "State"),
           sep    = ", ")%>% 
  
  # 5.2 Add the total price (price * quantity) 
  # Add a column to a tibble that uses a formula-style calculation of other columns
  mutate(total.price = quantity* price) %>%
  
  # 5.3 Optional: Reorganize. Using select to grab or remove unnecessary columns
  # 5.3.1 by exact column name
  select(-...1, -gender) %>%
  
  # 5.3.2 by a pattern
  # You can use the select_helpers to define patterns. 
  # Type ?ends_with and click on Select helpers in the documentation
  select(-ends_with(".id"))%>%
  
  # 5.3.3 Actually we need the column "order.id". Let's bind it back to the data
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  
  # 5.3.4 You can reorder the data by selecting the columns in your desired order.
  # You can use select_helpers like contains() or everything()
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,
         everything()) %>%
  
  # 5.4 Rename columns because we actually wanted underscores instead of the dots
  # (one at the time vs. multiple at once)
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))

```
## Plotting 
```{r}
# 6.2 Sales by Year and State ----
# Step 1 - Manipulate
sales_by_state_year_tbl <-bike_orderlines_wrangled_city_separated_tbl %>%
  
  # Select columns and add a year
  select(order_date, total_price, State) %>%
  mutate(year = year(order_date)) %>%
  
  # Group by and summarize year and main catgegory
  group_by(State, year) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

# Rotate plot: 
theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  
  labs(
    title    = "States revenue by year",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )
sales_by_state_year_tbl%>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = State)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  
  # Facet
  facet_wrap(~ State) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by State and year",
    subtitle = "Each product category has an upward trend",
    fill = "State" # Changes the legend name
  )
# Rotate plot: 
theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  
  labs(
    title    = "States revenue by year",
    x = "", # Override defaults for x and y
    y = "Revenue"
  )
```

## Writing files 
```{r}
library("writexl")
sales_by_state_year_tbl %>%
  write_xlsx("DS_101/00_data/01_bike_sales/02_wrangled_data/bike_orderlines.xlsx")

# 7.2 CSV ----
sales_by_state_year_tbl%>% 
  write_csv("DS_101/00_data/01_bike_sales/02_wrangled_data/bike_orderlines.csv")

# 7.3 RDS ----
sales_by_state_year_tbl %>% 
  write_rds("DS_101/00_data/01_bike_sales/02_wrangled_data/bike_orderlines.rds")
```

# Data Acqusition
## Libraries
```{r}
library(RSQLite)
library(dplyr)
library(httr)
library(glue)
library(jsonlite)
library(keyring)
library(rvest)
library(stringr)
library(stringi)
library(purrr)
library(xopen)
library(tibble)
library(curl)
```

## Get Data via API
```{r}
url= "https://api.agify.io?name=bella"
resp <- GET(url)
rawToChar(resp$content)
resp %>% 
  .$content %>% 
  rawToChar() %>% 
  fromJSON()

```
## Create Database
```{r}
get_bike_data <- function(url) {
  
  html_bike_category <- read_html(url)
  
  # Get the URLs
  bike_url_tbl  <- html_bike_category %>%
    html_nodes(css = ".catalog-category-bikes__title-text") %>%
    html_text()%>%
    enframe(name = "No.", value = "Bike.Name")
   bike_database_tbl<-bike_url_tbl%>% mutate(price=html_bike_category%>%html_nodes(css =".catalog-category-bikes__price-title")%>% html_text())
}
url= "https://www.rosebikes.de/ebike"
bike_tableout<-get_bike_data(url)
saveRDS(bike_tableout,"Task2_table.rds")


```

# Data Wrangling 
## Patents analysis
```{r}
#Patents analysis ----
# Importing data: ---- 
library(vroom)
# Tidyverse
library(tidyverse)

# Data Table
library(data.table)

# Counter
library(tictoc)
# 2.0 DATA IMPORT ----

# Patents: ----

col_types <- list(
  id = col_character(),
  date = col_date("%Y-%m-%d"),
  num_claims = col_double()
)

patent_tbl <- vroom(
  file       = "patent.tsv", 
  delim      = "\t", 
  col_types  = col_types,
  na         = c("", "NA", "NULL")
)



#Assignee_id = id,
# Assignee: ----

col_types_assignee <- list(
  id = col_character(),
  type = col_character(),
  organization = col_character()
)

assignee_tbl <- vroom(
  file       = "assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types_assignee,
  na         = c("", "NA", "NULL")
)


# Patent assignee: ----

col_types_patent_assignee <- list(
  patent_id = col_character(),
  assignee_id = col_character()
)


patent_assignee_tbl <- vroom(
  file       = "patent_assignee.tsv", 
  delim      = "\t", 
  col_types  = col_types_patent_assignee,
  na         = c("", "NA", "NULL")
)









col_types_uspc <- list(
  patent_id = col_character(),
  mainclass_id = col_number(),
  sequence = col_number()
)


uspc_tbl <- vroom(
  file       = "uspc.tsv", 
  delim      = "\t", 
  col_types  = col_types_uspc,
  na         = c("", "NA", "NULL")
)


# 3.1 Acquisition Data ----

setDT(assignee_tbl)
setDT(patent_tbl)
setDT(patent_assignee_tbl)
setDT(uspc_tbl)

patent_tbl %>% glimpse()
assignee_tbl %>% glimpse()
patent_assignee_tbl %>% glimpse()
uspc_tbl %>% glimpse()


# 4.0 DATA WRANGLING ----

# Target type = 2


# Start the analysis ----
#########################################################################
# Q1.Patent Dominance: What US company / corporation has the most patents? 
# List the 10 US companies with the most assigned/granted patents.
## Output: 
#########################################################################

# 4.1 summarize and count:



setnames(assignee_tbl, "id", "assignee_id")

combined_data <- merge(x = patent_assignee_tbl, y = assignee_tbl, by = "assignee_id")


us_patents <- combined_data %>%
  filter(type == 2)%>%
  filter(!is.na(patent_id) || !is.na(organization)) %>%
  select(-type, -assignee_id)%>% 
  group_by(organization) %>%
  count(patent_id) %>%
  select(-patent_id)%>%
  summarise(total = sum(n))%>%
  arrange(desc(total))   

us_top_10 <- us_patents %>% slice(1:10)


#########################################################################
# Q2. Recent patent acitivity: What US company had the most patents granted in 2019? 
#List the top 10 companies with the most new granted patents for 2019.
#########################################################################


tbl_2 <- patent_tbl %>%   
         separate(col  = date,
         into = c("year", "month", "day"),
          sep  = "-", remove = TRUE) %>%
          mutate(
              month = as.numeric(month)
            )%>%
          filter(month == 01)%>%
          select(-year, -day)

setnames(tbl_2, "id", "patent_id")
combined_data_2 <- merge(x = tbl_2, y = combined_data, by = "patent_id")

us_top10_2014_01 <- combined_data_2%>%
                    filter(type == 2)%>%
                    filter(!is.na(patent_id) || !is.na(organization)) %>%
                    select(organization, patent_id) %>%
                    group_by(organization) %>%
                    count(patent_id) %>%   
                    summarise(total_patents = sum(n))%>%
                    arrange(desc(total_patents)) %>% slice(1:10)  

us_top10_2014_01_new <- combined_data_2%>%
                        filter(type == 2 & num_claims == 1)%>%
                        filter(!is.na(patent_id) || !is.na(organization)) %>%
                        select(organization, patent_id) %>%
                        group_by(organization) %>%
                        count(patent_id) %>%   
                        summarise(total_patents = sum(n))%>%
                        arrange(desc(total_patents)) %>% slice(1:10)
                  
 #########################################################################
# Q. Innovation in Tech: What is the most innovative tech sector? 
# What is the most innovative tech sector? For the top 10 companies (worldwide)
# with the most patents, what are the top 5 USPTO tech main classes?
#########################################################################

combined_data_3 <- merge(x = uspc_tbl, y = combined_data_2, by = "patent_id")



top10_worlwide_patents <- combined_data_3  %>%
                  filter(!is.na(patent_id) || !is.na(organization))%>%
                  group_by(organization) %>%
                  arrange(desc(mainclass_id)) %>% # set mainclass order first, the result will be sorted automatically 
                  count(patent_id) %>%
                  select(-patent_id)%>%
                  summarise(total_patents_wordwide = sum(n))%>%
                  ungroup() %>%
                  arrange(desc(total_patents_wordwide)) %>% slice(1:10)  

top10_worlwid_top5_upts_ <- top10_worlwide_patents %>% slice(1:5)  









```

# Data Visualization
## Libraries
```{r}
library(tidyverse)
library(scales)
library(ggplot2)
library(lubridate)
library(ggthemes)
library(dbplyr)

```

## Map Time cumulative Covid-19 cases
```{r}
#importing data


covid_data_tbl <- read_csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")


# creating table for chart
covid_data_modified<-covid_data_tbl%>%
  select(countriesAndTerritories,cases,day,month,year)%>%
  relocate(month,day,year)%>%
  filter(year==2020,month>1)%>%
  filter(day!=1,countriesAndTerritories=="France" | countriesAndTerritories=="Germany" | countriesAndTerritories=="Spain" | countriesAndTerritories=="United_Kingdom" | countriesAndTerritories=="United_States_of_America")%>%
  group_by(month,countriesAndTerritories)%>%
  summarize(total_cases_per_month=sum(cases))%>%
  ungroup()

#data visualization 
covid_data_modified%>% ggplot(aes(month, total_cases_per_month, color = countriesAndTerritories))+
  geom_smooth(method = "loess", span=0.2) +
  
  # same as above, with explicit scales
  scale_y_continuous(labels = scales::dollar_format(scale = 1/1e6, 
                                                    prefix = "",
                                                    suffix = "M"))+
  scale_x_continuous(breaks = seq(2, 11, by = 1), labels = c("Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov"))+
  geom_label(aes(label=total_cases_per_month), 
             hjust = "inward",
             size  = 3,
             color = RColorBrewer::brewer.pal(n = 11, name = "RdBu")[11])+

  labs(
    title = "CovID-19 confirmed cases worldwide ",
    subtitle = "as of 11/02/2020. Europe is not included",
    caption = "",
    x = "Year 2020",
    y = "Cumulative cases(M)",
    color = "Country" # Legend text
  )

theme_dark () +
  theme(
    title = element_text(face = "bold", color = "#08306B")
    
  )
```
## Distribution of mourtality rate
```{r}
library(maps)

#importing data


covid_data_tbl <- read_csv("https://opendata.ecdc.europa.eu/covid19/casedistribution/csv")

world <- map_data("world")%>%mutate(across(region, str_replace_all, "_", " ")) %>%
  mutate(region = case_when(
    
    region == "UK"~ "United_Kingdom",
    region == "USA"~"United_States_of_America" ,
    region == "Czech_Republic"~"Czechia",
    TRUE ~ region
    
  ))
covid_data_tbl%>%mutate(across(countriesAndTerritories, str_replace_all, "_", " ")) %>%
  mutate(countriesAndTerritories = case_when(
    
    countriesAndTerritories == "United Kingdom" ~ "United_Kingdom",
    countriesAndTerritories == "United_States_of_America" ~ "United States of America",
    countriesAndTerritories == "Czechia"~"Czechia",
    TRUE ~ countriesAndTerritories
    
  ))

#manipulation of world data table
world_map<-world%>%select(region,long,lat,group)%>%rename(countriesAndTerritories=region)


#manipulation of covid data table
covid_modified_data_tbl<- covid_data_tbl%>%select(day,month,year,countriesAndTerritories,deaths,popData2019)%>%
  group_by(year,countriesAndTerritories,popData2019)%>%
  summarise(total_death=sum(deaths))%>%
  ungroup()%>%
  mutate(mortality_rate=(total_death/popData2019)*100)

#merging data between 2 tables 
All_data_tbl<-left_join(covid_modified_data_tbl,world_map,by="countriesAndTerritories")%>%filter(year==2020)


#first layer of the map
world_map <- map_data("world")
ggplot(world_map, aes(x = long, y = lat, group = group)) +
  geom_polygon(fill="lightgray", colour = "black",size=0.1)

#second layer of the map
ggplot(data=All_data_tbl, aes(x=long, y=lat, group = group))+
  geom_polygon(aes(fill = mortality_rate), color = "red",size=0.1)+
  scale_fill_viridis_c(option = "C", alpha = 0.75 )

  


```

